version: "3.9"

services:

  customer-auth:
    build:
      context: ./customer-auth
    container_name: customer-auth
    hostname: customer-auth
    image: martian-bank-customer-auth
    ports:
      - "8000:8000"
    env_file:
      - ./customer-auth/.env
    restart: always
    networks:
      - bankapp-network

  atm-locator:
    build:
      context: ./atm-locator
    container_name: atm-locator
    hostname: martian-bank-atm-locator
    image: martian-bank-atm-locator
    ports:
      - "8001:8001"
    env_file:
      - ./atm-locator/.env
    restart: always
    networks:
      - bankapp-network
  
  dashboard:
    container_name: dashboard
    hostname: dashboard
    ports:
      - "5000:5000"
    restart: always
    image: martian-bank-dashboard
    build:
      context: .
      dockerfile: dashboard/Dockerfile
      platforms:
        - "linux/amd64"
    environment:
      ACCOUNT_HOST: accounts
      TRANSACTION_HOST: transactions
      LOAN_HOST: loan
    networks:
      - bankapp-network
    
  accounts:
    build:
      context: .
      dockerfile: accounts/Dockerfile
      platforms:
        - "linux/amd64"
    container_name: accounts
    hostname: accounts
    image: martian-bank-accounts
    restart: always
    networks:
      - bankapp-network

  loan:
    build:
      context: .
      dockerfile: loan/Dockerfile
      platforms:
        - "linux/amd64"
    container_name: loan
    hostname: loan
    image: martian-bank-loan
    restart: always
    networks:
      - bankapp-network

  transactions:
    build:
      context: .
      dockerfile: transactions/Dockerfile
      platforms:
        - "linux/amd64"
    container_name: transactions
    hostname: martian-bank-transactions
    image: martian-bank-transactions
    restart: always
    networks:
      - bankapp-network 

networks:
  bankapp-network:
    driver: bridge
