# You can tell Kubernetes how to identify your microservice by using labels

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dashboard
    labels:
        app: dashboard
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dashboard
    template:
        metadata:
            labels:
                app: dashboard
        spec:
            containers:
                - name: dashboard
                  image: docker.io/waris95/bankapp-dashboard
                  env:
                      - name: ACCOUNT_HOST
                        value: accounts
                      - name: LOAN_HOST
                        value: loan
                      - name: TRANSACTION_HOST
                        value: transactions
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: accounts
    labels:
        app: accounts
spec:
    replicas: 1
    selector:
        matchLabels:
            app: accounts
    template:
        metadata:
            labels:
                app: accounts
        spec:
            containers:
                - name: accounts
                  image: docker.io/waris95/bankapp-accounts
# loan 
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: loan
    labels:
        app: loan
spec: 
    replicas: 1
    selector:
        matchLabels:
            app: loan
    template:
        metadata:
            labels:
                app: loan
        spec:
            containers:
                - name: loan
                #   registry: docker.io
                  image: docker.io/waris95/bankapp-loan

# transactions

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: transactions
    labels:
        app: transactions
spec:
    replicas: 1
    selector:
        matchLabels:
            app: transactions
    template:
        metadata:
            labels:
                app: transactions
        spec:
            containers:
                - name: transactions
                  image: docker.io/waris95/bankapp-transactions


# customer-auth

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: customer-auth
    labels:
        app: customer-auth
spec:    
    replicas: 1
    selector:
        matchLabels:
            app: customer-auth
    template:
        metadata:
            labels:
                app: customer-auth
        spec:
            containers:
                - name: customer-auth
                  image: docker.io/waris95/bankapp-customer-auth


# atm-locator
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: atm-locator
    labels:
        app: atm-locator
spec:
    replicas: 1
    selector:
        matchLabels:
            app: atm-locator
    template:
        metadata:
            labels:
                app: atm-locator
        spec:
            containers:
                - name: atm-locator
                  image: docker.io/waris95/bankapp-atm-locator

# nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
    labels:
        app: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  image: docker.io/waris95/bankapp-nginx
                  







# Service 


---
apiVersion: v1
kind: Service
metadata:
    name: dashboard
spec:
    type: LoadBalancer # This is the only line that is different from the previous service that this is accessible from outside
    selector:
        app: dashboard
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    name: accounts
spec:
    selector:
        app: accounts
    ports:
        - protocol: TCP
          port: 50051
          targetPort: 50051

---
apiVersion: v1
kind: Service
metadata:
    name: loan
spec:
    selector:
        app: loan
    ports:
        - protocol: TCP
          port: 50053
          targetPort: 50053

---
apiVersion: v1
kind: Service
metadata:
    name: transactions
spec:
    selector:
        app: transactions
    ports:
        - protocol: TCP
          port: 50052
          targetPort: 50052



