apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: docker.io/waris95/martian-bank-accounts

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-accounts
spec:
  selector:
    app: accounts
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
