apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-atm-locator
  labels:
    app: atm-locator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atm-locator
  template:
    metadata:
      labels:
        app: atm-locator
    spec:
      containers:
        - name: atm-locator
          image: docker.io/jashmehta3300/martian-bank-atm-locator

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-atm-locator
spec:
  selector:
    app: atm-locator
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
