apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-customer-auth
  labels:
    app: customer-auth
spec:    
    replicas: 1
    selector:
        matchLabels:
            app: customer-auth
    template:
        metadata:
            labels:
                app: customer-auth
        spec:
            containers:
                - name: customer-auth
                  image: docker.io/jashmehta3300/martian-bank-customer-auth
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-customer-auth
spec:
  selector:
    app: customer-auth
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
