apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: docker.io/jashmehta3300/martian-bank-ui

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
